### ISSUE TITLE
pytorch安装问题

### ISSUE THREAD

**Issue by ShunhuaLin7** [GRF-Sunomikp31/Robomaster-skyteam#2]
报错信息如下
(base) C:\Users\18709>conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia
Collecting package metadata (current_repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/pytorch/win-64/current_repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
'https://conda.anaconda.org/pytorch/win-64'
似乎是网络链接问题，是国内这个链接被墙了吗？

**Comment by GRF-Sunomikp31** [comment]
貌似是源（source）的问题

**Comment by ShunhuaLin7** [comment]
我已经收到你的邮件，会尽快回复你。————————————这是一封自动回复邮件。
